### PR TITLE
Update science.js

### PR DESCRIPTION
**Pull request by ceisenbach**
A grid function. 
For creating a grid background.

### CODE REVIEW

**Comment by hedbergj** [comment]
Hmm. Two things.

1. So, when I make a grid using this, my CPU usage for the browser goes up to 80-90%. (Check your activity monitor and see if you get something similar) This means there are some inefficiencies we should deal with. Maybe lines, not rectangles?

2. The science library file, `science.js` is made up of smaller files, in the `src` folder. I use grunt to assemble them into one file. So, pull requests on science library need to be on one of the smaller, src files, not the main `science.js` file.

```
function setup(){
canvas= createCanvas(500,500);
}

function draw(){
  background(100);
  myGrid = new Grid(20,10);
  myGrid.update();

}
function Grid(r,mag){
   this.update = function(){
     for(this.i = 0; this.i< r; this.i++){
      for(this.j = 0; this.j <r; this.j++){
      this.x = this.i * mag;
      this.y = this.j * mag;
      stroke(0);
      fill(255);
      rect(this.x,this.y,mag,mag);
      }
     }
   }
 }
```

**Comment by ChuckStern** [comment]
Thanks for the comments.
Regarding efficiency, I found that putting the grid into the setup function cuts down on cpu demand.

**Comment by hedbergj** [comment]
Yeah, you're right, that's were it should be. But I still get way too much cpu use. 

screen shot 2016-07-25 at 11 31 39 am

using the *line()* function would make more sense I think, since there will be way less repeated drawing. With the rectangles, each line is drawn twice since the rectangles overlap. Or maybe use the beginShape(LINES) like this:

```
 beginShape(LINES);
 for(i=0;i<nOfRows;i++){
       vertex(0,i*spacing);
       vertex(width,i*spacing);
     }
endShape();
```

That might do something.

**Comment by ChuckStern** [comment]
I meant perhaps putting 
``` mygrid.update ```
in the setup function as well. it cut my cpu demand to about 7%.

But I will see what happens with vertexes or lines.
I used rectangles so it would be easy for the user to pass size arguments into the funtion, although  I could easily do that with lines or vertexes.

**Comment by hedbergj** [comment]
For sure it won't take up any resources in the `setup()` function, because, that only gets called  once, when the sketch first loads. But, then it will get drawn over the first time the `draw()` runs and you will loose the grid.

**Comment by ChuckStern** [comment]
Yeah I did think that _might_ be a problem

**Comment by ChuckStern** [comment]
I think this might be a good solution.
I used the ```createGraphics ``` function from p5.js 
you can put this in the setup function and then draw stuff on top.
I'll try and make it into a constructor function so the user can pass size and placement arguments into it.
  ```
  grid = createGraphics(width,height);
  grid.background(255);
  for(var i = 0 ; i < 10; i++){
  	for(var j = 0; j< 10 ; j++){
  		x = i * 30;
  		y = j * 30;
  		grid.fill(255);
  		grid.stroke(0);
  		grid.rect(x,y,30,30);
  		
  	}
  }
  image(grid,0,0,width,height);
```

**Comment by hedbergj** [comment]
Ok cool, give it a whirl - You’re still going to be better off with lines, not rectangles. Eg: if you have a 20 by 20 grid, that's 400 draw calls to make using rectangles. It would only take 20+20 = 40 lines to do the same thing. That’s an order of magnitude difference in processor demands. You would want to leave open the possibility that the grid could be used in a draw() function also. Also, it would allow for other things like making every fifth line a little thicker for clarity.

image

**Comment by ChuckStern** [comment]
Most definitely.
I'll change it up.

**Pull request closed without merging**
